### ISSUE TITLE
Users can join twice after end of a game 

### ISSUE THREAD

**Issue by cevn** [eraether/WatchWordBot#1]
Stephen Otunba [4:48 PM]  
join

Watch WordsBOT [4:48 PM]  
steveo has joined the game!

[4:48]  
Here are the teams:
[​_Red team_​]
sdhar (Leader)
mattb
steveo
[​_Blue team_​]
eric (Leader)
shruthi

サミア ダー [4:48 PM]  
join

Watch WordsBOT [4:48 PM]  
sdhar has joined the game!

[4:48]  
Here are the teams:
[​_Red team_​]
sdhar (Leader)
mattb
steveo
[​_Blue team_​]
eric (Leader)
shruthi
sdhar

**Comment by eraether** [comment]
Need a way to reproduce this.

**Comment by eraether** [comment]
No way to reproduce.  Closing.
