### ISSUE TITLE
Board words too abstract

### ISSUE THREAD

**Issue by cevn** [eraether/WatchWordBot#3]
imo should be more things and less .. whatever it is now

```
[ Cancel     ][ Absence    ][ Embryo     ][ Apologise  ][ Despise    ]
[ Balcony    ][ Cheese     ][ <Red>      ][ Ambition   ][ Cake       ]
[ Linen      ][ Wonder     ][ Wardrobe   ][ Chaos      ][ Bitch      ]
[ Suggestion ][ Mole       ][ Pardon     ][ Football   ][ Complain   ]
[ Soldier    ][ Publish    ][ <Blue>     ][ Spy        ][ Tunnel     ]
```

**Comment by eraether** [comment]
The least abstract things are nouns, followed by verbs, followed by adjectives

We could split up the current words into groups based on the parts of speech, then take, say, 80% from the noun list, 15% from the verbs and 5% from the adjectives.

**Comment by eraether** [comment]
Seems to be slowly getting fixed by incoming pull requests.
