### ISSUE TITLE
Store match history

### ISSUE THREAD

**Issue by eraether** [eraether/WatchWordBot#46]

**Comment by eraether** [comment]
Created by eugene (Eugene Raether)

**Comment by msblum** [comment]
to specify, this ticket is about storing match information for advanced player statistics and should include all player actions and their results (with the exception of the actual words guessed and clues given). For example in a round where the cluegiver gives a 'word 5' clue, i would like to have stored the number of words the cluegiver intended to have guessed (5) and the number of correct guesses by the guessing team. Additionally match-wide I would like to keep track of number of wins and losses as well as number of clues needed to win (assuming asesino doesn't figure in). Any other stats that might be interesting you can add as well!

**Comment by eraether** [comment]
In addition to high-level statistics it might be equally interesting to simply store every user action taken during a game, including chat messages.  This would also help when moderating abuse.

**Comment by eraether** [comment]
Won't fix.  Out of scope.
